// Common Nerd Font icons for Oh My Posh prompts
// Source: https://www.nerdfonts.com/cheat-sheet

export interface NerdFontIcon {
  name: string;
  code: string;
  char: string;
  category: string;
}

export const NERD_FONT_ICONS: NerdFontIcon[] = [
  // Powerline symbols
  { name: 'Right Arrow', code: 'E0B0', char: '\ue0b0', category: 'Powerline' },
  { name: 'Right Arrow Thin', code: 'E0B1', char: '\ue0b1', category: 'Powerline' },
  { name: 'Left Arrow', code: 'E0B2', char: '\ue0b2', category: 'Powerline' },
  { name: 'Left Arrow Thin', code: 'E0B3', char: '\ue0b3', category: 'Powerline' },
  { name: 'Right Rounded', code: 'E0B4', char: '\ue0b4', category: 'Powerline' },
  { name: 'Right Rounded Thin', code: 'E0B5', char: '\ue0b5', category: 'Powerline' },
  { name: 'Left Rounded', code: 'E0B6', char: '\ue0b6', category: 'Powerline' },
  { name: 'Left Rounded Thin', code: 'E0B7', char: '\ue0b7', category: 'Powerline' },
  { name: 'Right Flame', code: 'E0BC', char: '\ue0bc', category: 'Powerline' },
  { name: 'Left Flame', code: 'E0BE', char: '\ue0be', category: 'Powerline' },
  { name: 'Right Pixelated', code: 'E0C0', char: '\ue0c0', category: 'Powerline' },
  { name: 'Left Pixelated', code: 'E0C2', char: '\ue0c2', category: 'Powerline' },
  { name: 'Honeycomb', code: 'E0C4', char: '\ue0c4', category: 'Powerline' },
  { name: 'Honeycomb Outline', code: 'E0C6', char: '\ue0c6', category: 'Powerline' },
  { name: 'Ice', code: 'E0C8', char: '\ue0c8', category: 'Powerline' },
  { name: 'Trapezoid Top', code: 'E0CC', char: '\ue0cc', category: 'Powerline' },
  { name: 'Trapezoid Bottom', code: 'E0CE', char: '\ue0ce', category: 'Powerline' },
  { name: 'Right Semi-circle', code: 'E0D2', char: '\ue0d2', category: 'Powerline' },
  { name: 'Left Semi-circle', code: 'E0D4', char: '\ue0d4', category: 'Powerline' },
  
  // File/Folder icons
  { name: 'Folder', code: 'F07B', char: '\uf07b', category: 'Files' },
  { name: 'Folder Open', code: 'F07C', char: '\uf07c', category: 'Files' },
  { name: 'File', code: 'F15B', char: '\uf15b', category: 'Files' },
  { name: 'File Code', code: 'F1C9', char: '\uf1c9', category: 'Files' },
  { name: 'File Text', code: 'F15C', char: '\uf15c', category: 'Files' },
  { name: 'File Archive', code: 'F1C6', char: '\uf1c6', category: 'Files' },
  { name: 'File PDF', code: 'F1C1', char: '\uf1c1', category: 'Files' },
  { name: 'File Image', code: 'F1C5', char: '\uf1c5', category: 'Files' },
  { name: 'File Video', code: 'F1C8', char: '\uf1c8', category: 'Files' },
  { name: 'File Audio', code: 'F1C7', char: '\uf1c7', category: 'Files' },
  { name: 'Home', code: 'F015', char: '\uf015', category: 'Files' },
  { name: 'Desktop', code: 'F108', char: '\uf108', category: 'Files' },
  { name: 'Download Folder', code: 'E5FF', char: '\ue5ff', category: 'Files' },
  
  // Git icons
  { name: 'Git Branch', code: 'E0A0', char: '\ue0a0', category: 'Git' },
  { name: 'Git Merge', code: 'E0A1', char: '\ue0a1', category: 'Git' },
  { name: 'Git Commit', code: 'F417', char: '\uf417', category: 'Git' },
  { name: 'GitHub', code: 'F09B', char: '\uf09b', category: 'Git' },
  { name: 'GitLab', code: 'F296', char: '\uf296', category: 'Git' },
  { name: 'Bitbucket', code: 'F171', char: '\uf171', category: 'Git' },
  { name: 'Git Pull Request', code: 'E229', char: '\ue229', category: 'Git' },
  { name: 'Git Compare', code: 'E225', char: '\ue225', category: 'Git' },
  
  // Language icons
  { name: 'Python', code: 'E235', char: '\ue235', category: 'Languages' },
  { name: 'Node.js', code: 'E718', char: '\ue718', category: 'Languages' },
  { name: 'JavaScript', code: 'E74E', char: '\ue74e', category: 'Languages' },
  { name: 'TypeScript', code: 'E628', char: '\ue628', category: 'Languages' },
  { name: 'React', code: 'E7BA', char: '\ue7ba', category: 'Languages' },
  { name: 'Vue', code: 'E6A0', char: '\ue6a0', category: 'Languages' },
  { name: 'Angular', code: 'E753', char: '\ue753', category: 'Languages' },
  { name: 'Go', code: 'E724', char: '\ue724', category: 'Languages' },
  { name: 'Rust', code: 'E7A8', char: '\ue7a8', category: 'Languages' },
  { name: 'Java', code: 'E738', char: '\ue738', category: 'Languages' },
  { name: 'C', code: 'E61E', char: '\ue61e', category: 'Languages' },
  { name: 'C++', code: 'E61D', char: '\ue61d', category: 'Languages' },
  { name: 'C#', code: 'E648', char: '\ue648', category: 'Languages' },
  { name: 'PHP', code: 'E73D', char: '\ue73d', category: 'Languages' },
  { name: 'Ruby', code: 'E739', char: '\ue739', category: 'Languages' },
  { name: 'Perl', code: 'E769', char: '\ue769', category: 'Languages' },
  { name: 'Swift', code: 'E755', char: '\ue755', category: 'Languages' },
  { name: 'Kotlin', code: 'E634', char: '\ue634', category: 'Languages' },
  { name: 'Scala', code: 'E737', char: '\ue737', category: 'Languages' },
  { name: 'Elixir', code: 'E62D', char: '\ue62d', category: 'Languages' },
  { name: 'Haskell', code: 'E777', char: '\ue777', category: 'Languages' },
  { name: 'Lua', code: 'E620', char: '\ue620', category: 'Languages' },
  { name: 'R', code: 'F25D', char: '\uf25d', category: 'Languages' },
  { name: 'Dart', code: 'E798', char: '\ue798', category: 'Languages' },
  { name: 'HTML5', code: 'E736', char: '\ue736', category: 'Languages' },
  { name: 'CSS3', code: 'E749', char: '\ue749', category: 'Languages' },
  { name: 'Sass', code: 'E603', char: '\ue603', category: 'Languages' },
  { name: 'Less', code: 'E758', char: '\ue758', category: 'Languages' },
  { name: 'JSON', code: 'E60B', char: '\ue60b', category: 'Languages' },
  { name: 'XML', code: 'E619', char: '\ue619', category: 'Languages' },
  { name: 'Markdown', code: 'E609', char: '\ue609', category: 'Languages' },
  
  // Cloud/DevOps icons
  { name: 'Docker', code: 'F308', char: '\uf308', category: 'DevOps' },
  { name: 'Kubernetes', code: 'E202', char: '\ue202', category: 'DevOps' },
  { name: 'AWS', code: 'E7AD', char: '\ue7ad', category: 'DevOps' },
  { name: 'Azure', code: 'EBD8', char: '\uebd8', category: 'DevOps' },
  { name: 'Google Cloud', code: 'E7B2', char: '\ue7b2', category: 'DevOps' },
  { name: 'Terraform', code: 'E20F', char: '\ue20f', category: 'DevOps' },
  { name: 'Jenkins', code: 'E767', char: '\ue767', category: 'DevOps' },
  { name: 'CircleCI', code: 'E26B', char: '\ue26b', category: 'DevOps' },
  { name: 'Travis CI', code: 'E77E', char: '\ue77e', category: 'DevOps' },
  { name: 'Ansible', code: 'E65F', char: '\ue65f', category: 'DevOps' },
  { name: 'Vagrant', code: 'F27D', char: '\uf27d', category: 'DevOps' },
  { name: 'Nginx', code: 'E776', char: '\ue776', category: 'DevOps' },
  { name: 'Apache', code: 'E909', char: '\ue909', category: 'DevOps' },
  
  // System icons
  { name: 'Terminal', code: 'F120', char: '\uf120', category: 'System' },
  { name: 'Console', code: 'F489', char: '\uf489', category: 'System' },
  { name: 'Command', code: 'F489', char: '\uf489', category: 'System' },
  { name: 'User', code: 'F007', char: '\uf007', category: 'System' },
  { name: 'Users', code: 'F0C0', char: '\uf0c0', category: 'System' },
  { name: 'Crown (Admin)', code: 'F521', char: '\uf521', category: 'System' },
  { name: 'Shield', code: 'F132', char: '\uf132', category: 'System' },
  { name: 'Lock', code: 'F023', char: '\uf023', category: 'System' },
  { name: 'Lock Open', code: 'F3C1', char: '\uf3c1', category: 'System' },
  { name: 'Key', code: 'F084', char: '\uf084', category: 'System' },
  { name: 'Clock', code: 'F017', char: '\uf017', category: 'System' },
  { name: 'Stopwatch', code: 'F2F2', char: '\uf2f2', category: 'System' },
  { name: 'Hourglass', code: 'F254', char: '\uf254', category: 'System' },
  { name: 'Lightning', code: 'F0E7', char: '\uf0e7', category: 'System' },
  { name: 'Bolt', code: 'F0E7', char: '\uf0e7', category: 'System' },
  { name: 'Fire', code: 'F06D', char: '\uf06d', category: 'System' },
  { name: 'Snowflake', code: 'F2DC', char: '\uf2dc', category: 'System' },
  { name: 'Sun', code: 'F185', char: '\uf185', category: 'System' },
  { name: 'Moon', code: 'F186', char: '\uf186', category: 'System' },
  { name: 'Cog', code: 'F013', char: '\uf013', category: 'System' },
  { name: 'Cogs', code: 'F085', char: '\uf085', category: 'System' },
  { name: 'Sliders', code: 'F1DE', char: '\uf1de', category: 'System' },
  { name: 'Check', code: 'F00C', char: '\uf00c', category: 'System' },
  { name: 'Check Circle', code: 'F058', char: '\uf058', category: 'System' },
  { name: 'Times (X)', code: 'F00D', char: '\uf00d', category: 'System' },
  { name: 'Times Circle', code: 'F057', char: '\uf057', category: 'System' },
  { name: 'Plus', code: 'F067', char: '\uf067', category: 'System' },
  { name: 'Plus Circle', code: 'F055', char: '\uf055', category: 'System' },
  { name: 'Minus', code: 'F068', char: '\uf068', category: 'System' },
  { name: 'Minus Circle', code: 'F056', char: '\uf056', category: 'System' },
  { name: 'Exclamation', code: 'F12A', char: '\uf12a', category: 'System' },
  { name: 'Exclamation Triangle', code: 'F071', char: '\uf071', category: 'System' },
  { name: 'Question', code: 'F128', char: '\uf128', category: 'System' },
  { name: 'Question Circle', code: 'F059', char: '\uf059', category: 'System' },
  { name: 'Info', code: 'F129', char: '\uf129', category: 'System' },
  { name: 'Info Circle', code: 'F05A', char: '\uf05a', category: 'System' },
  { name: 'Star', code: 'F005', char: '\uf005', category: 'System' },
  { name: 'Star Half', code: 'F089', char: '\uf089', category: 'System' },
  { name: 'Heart', code: 'F004', char: '\uf004', category: 'System' },
  { name: 'Bell', code: 'F0F3', char: '\uf0f3', category: 'System' },
  { name: 'Bookmark', code: 'F02E', char: '\uf02e', category: 'System' },
  { name: 'Flag', code: 'F024', char: '\uf024', category: 'System' },
  { name: 'Tag', code: 'F02B', char: '\uf02b', category: 'System' },
  { name: 'Tags', code: 'F02C', char: '\uf02c', category: 'System' },
  { name: 'Calendar', code: 'F073', char: '\uf073', category: 'System' },
  { name: 'List', code: 'F03A', char: '\uf03a', category: 'System' },
  { name: 'Eye', code: 'F06E', char: '\uf06e', category: 'System' },
  { name: 'Eye Slash', code: 'F070', char: '\uf070', category: 'System' },
  { name: 'Pencil', code: 'F040', char: '\uf040', category: 'System' },
  { name: 'Pen', code: 'F304', char: '\uf304', category: 'System' },
  { name: 'Trash', code: 'F1F8', char: '\uf1f8', category: 'System' },
  { name: 'Ban', code: 'F05E', char: '\uf05e', category: 'System' },
  { name: 'Circle', code: 'F111', char: '\uf111', category: 'System' },
  { name: 'Dot Circle', code: 'F192', char: '\uf192', category: 'System' },
  { name: 'Power Off', code: 'F011', char: '\uf011', category: 'System' },
  
  // Arrows & indicators
  { name: 'Arrow Right', code: 'F061', char: '\uf061', category: 'Arrows' },
  { name: 'Arrow Left', code: 'F060', char: '\uf060', category: 'Arrows' },
  { name: 'Arrow Up', code: 'F062', char: '\uf062', category: 'Arrows' },
  { name: 'Arrow Down', code: 'F063', char: '\uf063', category: 'Arrows' },
  { name: 'Arrow Circle Right', code: 'F0A9', char: '\uf0a9', category: 'Arrows' },
  { name: 'Arrow Circle Left', code: 'F0A8', char: '\uf0a8', category: 'Arrows' },
  { name: 'Arrow Circle Up', code: 'F0AA', char: '\uf0aa', category: 'Arrows' },
  { name: 'Arrow Circle Down', code: 'F0AB', char: '\uf0ab', category: 'Arrows' },
  { name: 'Chevron Right', code: 'F054', char: '\uf054', category: 'Arrows' },
  { name: 'Chevron Left', code: 'F053', char: '\uf053', category: 'Arrows' },
  { name: 'Chevron Up', code: 'F077', char: '\uf077', category: 'Arrows' },
  { name: 'Chevron Down', code: 'F078', char: '\uf078', category: 'Arrows' },
  { name: 'Angle Right', code: 'F105', char: '\uf105', category: 'Arrows' },
  { name: 'Angle Left', code: 'F104', char: '\uf104', category: 'Arrows' },
  { name: 'Angle Up', code: 'F106', char: '\uf106', category: 'Arrows' },
  { name: 'Angle Down', code: 'F107', char: '\uf107', category: 'Arrows' },
  { name: 'Angle Double Right', code: 'F101', char: '\uf101', category: 'Arrows' },
  { name: 'Angle Double Left', code: 'F100', char: '\uf100', category: 'Arrows' },
  { name: 'Angle Double Up', code: 'F102', char: '\uf102', category: 'Arrows' },
  { name: 'Angle Double Down', code: 'F103', char: '\uf103', category: 'Arrows' },
  { name: 'Caret Right', code: 'F0DA', char: '\uf0da', category: 'Arrows' },
  { name: 'Caret Left', code: 'F0D9', char: '\uf0d9', category: 'Arrows' },
  { name: 'Caret Up', code: 'F0D8', char: '\uf0d8', category: 'Arrows' },
  { name: 'Caret Down', code: 'F0D7', char: '\uf0d7', category: 'Arrows' },
  { name: 'Long Arrow Right', code: 'F178', char: '\uf178', category: 'Arrows' },
  { name: 'Long Arrow Left', code: 'F177', char: '\uf177', category: 'Arrows' },
  { name: 'Long Arrow Up', code: 'F176', char: '\uf176', category: 'Arrows' },
  { name: 'Long Arrow Down', code: 'F175', char: '\uf175', category: 'Arrows' },
  
  // Misc useful icons
  { name: 'Database', code: 'F1C0', char: '\uf1c0', category: 'Misc' },
  { name: 'Server', code: 'F233', char: '\uf233', category: 'Misc' },
  { name: 'HDD', code: 'F0A0', char: '\uf0a0', category: 'Misc' },
  { name: 'Cloud', code: 'F0C2', char: '\uf0c2', category: 'Misc' },
  { name: 'Cloud Upload', code: 'F0EE', char: '\uf0ee', category: 'Misc' },
  { name: 'Cloud Download', code: 'F0ED', char: '\uf0ed', category: 'Misc' },
  { name: 'Download', code: 'F019', char: '\uf019', category: 'Misc' },
  { name: 'Upload', code: 'F093', char: '\uf093', category: 'Misc' },
  { name: 'Sync', code: 'F021', char: '\uf021', category: 'Misc' },
  { name: 'Refresh', code: 'F01E', char: '\uf01e', category: 'Misc' },
  { name: 'Redo', code: 'F01E', char: '\uf01e', category: 'Misc' },
  { name: 'Undo', code: 'F0E2', char: '\uf0e2', category: 'Misc' },
  { name: 'Search', code: 'F002', char: '\uf002', category: 'Misc' },
  { name: 'Search Plus', code: 'F00E', char: '\uf00e', category: 'Misc' },
  { name: 'Search Minus', code: 'F010', char: '\uf010', category: 'Misc' },
  { name: 'Filter', code: 'F0B0', char: '\uf0b0', category: 'Misc' },
  { name: 'Bug', code: 'F188', char: '\uf188', category: 'Misc' },
  { name: 'Code', code: 'F121', char: '\uf121', category: 'Misc' },
  { name: 'Code Branch', code: 'E725', char: '\ue725', category: 'Misc' },
  { name: 'Wrench', code: 'F0AD', char: '\uf0ad', category: 'Misc' },
  { name: 'Hammer', code: 'F6E3', char: '\uf6e3', category: 'Misc' },
  { name: 'Tools', code: 'F0AD', char: '\uf0ad', category: 'Misc' },
  { name: 'Plug', code: 'F1E6', char: '\uf1e6', category: 'Misc' },
  { name: 'Link', code: 'F0C1', char: '\uf0c1', category: 'Misc' },
  { name: 'Unlink', code: 'F127', char: '\uf127', category: 'Misc' },
  { name: 'Chain', code: 'F0C1', char: '\uf0c1', category: 'Misc' },
  { name: 'Paperclip', code: 'F0C6', char: '\uf0c6', category: 'Misc' },
  { name: 'Share', code: 'F064', char: '\uf064', category: 'Misc' },
  { name: 'External Link', code: 'F08E', char: '\uf08e', category: 'Misc' },
  { name: 'Wifi', code: 'F1EB', char: '\uf1eb', category: 'Misc' },
  { name: 'Signal', code: 'F012', char: '\uf012', category: 'Misc' },
  { name: 'Rss', code: 'F09E', char: '\uf09e', category: 'Misc' },
  { name: 'Envelope', code: 'F0E0', char: '\uf0e0', category: 'Misc' },
  { name: 'Paper Plane', code: 'F1D8', char: '\uf1d8', category: 'Misc' },
  { name: 'Inbox', code: 'F01C', char: '\uf01c', category: 'Misc' },
  { name: 'Archive', code: 'F187', char: '\uf187', category: 'Misc' },
  { name: 'Box', code: 'F466', char: '\uf466', category: 'Misc' },
  { name: 'Cube', code: 'F1B2', char: '\uf1b2', category: 'Misc' },
  { name: 'Cubes', code: 'F1B3', char: '\uf1b3', category: 'Misc' },
  { name: 'Gift', code: 'F06B', char: '\uf06b', category: 'Misc' },
  { name: 'Trophy', code: 'F091', char: '\uf091', category: 'Misc' },
  { name: 'Certificate', code: 'F0A3', char: '\uf0a3', category: 'Misc' },
  { name: 'Rocket', code: 'F135', char: '\uf135', category: 'Misc' },
  { name: 'Compass', code: 'F14E', char: '\uf14e', category: 'Misc' },
  { name: 'Map', code: 'F279', char: '\uf279', category: 'Misc' },
  { name: 'Map Marker', code: 'F041', char: '\uf041', category: 'Misc' },
  { name: 'Location', code: 'F041', char: '\uf041', category: 'Misc' },
  { name: 'Globe', code: 'F0AC', char: '\uf0ac', category: 'Misc' },
  { name: 'Language', code: 'F1AB', char: '\uf1ab', category: 'Misc' },
  { name: 'Puzzle Piece', code: 'F12E', char: '\uf12e', category: 'Misc' },
  { name: 'Magic', code: 'F0D0', char: '\uf0d0', category: 'Misc' },
  { name: 'Wand', code: 'F0D0', char: '\uf0d0', category: 'Misc' },
];

export const ICON_CATEGORIES = [
  'All',
  'Powerline',
  'Files',
  'Git',
  'Languages',
  'DevOps',
  'System',
  'Arrows',
  'Misc',
] as const;

export type IconCategory = typeof ICON_CATEGORIES[number];
